---
# Install docker dependencies
- name: 'install docker dependencies'
  apt:
    name: ['apt-transport-https', 'ca-certificates']    
    state: 'present'
    update_cache: 'yes'

# Add docker repo apt key
- name: 'add docker repo apt key'
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    state: 'present'
  register: 'add_repository_key'
  ignore_errors: true

# Add docker repository
- name: 'add docker repository'
  apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: 'present'
    update_cache: 'yes'

# Install specific version of docker-ce package
- name: 'install docker-ce'
  apt:
    name: 'docker-ce={{ docker_version }}'
    state: 'present'

# Enable docker systemd service
- name: 'enable docker systemd service'
  service:
    name: 'docker'
    state: 'started'
    enabled: 'yes'

# Add users to docker group
- name: 'add users to docker group'
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: 'yes'
  with_items: '{{ docker_group_members }}'
  when: 'docker_group_members is defined'